# Generated by Django 3.1.7 on 2021-03-19 14:25

from django.db import migrations, models
import tracker_app.validator


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_app', '0002_auto_20210316_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True, validators=[tracker_app.validator.BadWordsValidation(('fuck', 'bullshit', 'asshole'))], verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='summary',
            field=models.CharField(max_length=50, validators=[tracker_app.validator.BadWordsValidation(('fuck', 'bullshit', 'asshole')), tracker_app.validator.capital_letter, tracker_app.validator.MinLengthValidator(10)], verbose_name='Заголовок'),
        ),
    ]
