# Generated by Django 3.1.7 on 2021-04-17 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_app', '0008_auto_20210417_1206'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': [('add_user_to_project', 'Добавить пользователя к проекту')]},
        ),
    ]
